version: '3.4'

services:
  web:
    build: 
      context: ./web
    ports:
      - "5173:5173" 
    volumes:
      - ./web:/web
  api:
    image: api
    build:
      context: ./api
    ports:
      - 5000:5000
    
