services:
  web:
    build: ./web
    ports:
      - "5173:5173"  # Map host port 3000 to container port 5173
    volumes:
      - ./web:/web
  api:
    build: ./api
    ports:
      - "5000:5000"  # Map host port 5000 to container port 5000
    volumes:
      - ./api:/api
